#!/bin/sh

if [ "X$1" = "Xstart" ]; then
  echo "S10setup: start"

##Compiler will insert mount commands##

  if [ ! -d /root/Data ] ; then
    echo "S10setup: Creating Data folder... "
    mkdir -pm 777 /root/Data
    sync
  fi

  # Check if NetworkManager system folder exists on userdata
  if [ ! -d /root/.sysconfig/NetworkManager ] ; then
    echo "S10setup: Creating .sysconfig folder... "
    mkdir -p /root/.sysconfig/NetworkManager
    cp -a /etc/NetworkManager/* /root/.sysconfig/NetworkManager/
    chmod 544 /root/.sysconfig/NetworkManager/dispatcher.d/*
    MAC=$(cat /sys/class/net/eth0/address)
    echo -e "[keyfile]\nunmanaged-devices=mac:$MAC" >> /root/.sysconfig/NetworkManager/NetworkManager.conf
    sync
  fi
  mount -o bind /root/.sysconfig/NetworkManager /etc/NetworkManager

  # Boot with performance, then switch to ondemand (kernel bug)
  CPU=/sys/devices/system/cpu/cpu0/cpufreq
  echo "S10setup: set cpu scaling governor"
  echo "ondemand" > $CPU/scaling_governor
  echo "S10setup: set cpu scaling min/max"
  # M1/M3 devices, limit to 600Mhz to keep audio hw from stalling
  echo "600000" > $CPU/scaling_min_freq
  # M1/M3 devices max out at 800Mhz
  echo "800000" > $CPU/scaling_max_freq

  echo "S10setup: done"
fi
