#!/bin/sh

if [ "X$1" = "Xstart" ]; then
  echo "S10setup: start"

  # Remount / RW
  echo "S10setup: remount / rw"
  mount -o remount,rw /

  # Make sure dropbear directory exists
  echo "S10setup: checking keys"
  if [ ! -d /etc/dropbear ]; then
    mkdir -p /etc/dropbear
  fi

  # Check for the Dropbear RSA key
  if [ ! -f /etc/dropbear/dropbear_rsa_host_key ]; then
    echo -n "generating rsa key... "
    /usr/bin/dropbearkey -t rsa -f /etc/dropbear/dropbear_rsa_host_key > /dev/null 2>&1
  fi

  # Check for the Dropbear DSS key
  if [ ! -f /etc/dropbear/dropbear_dss_host_key ]; then
    echo -n "generating dss key... "
    /usr/bin/dropbearkey -t dss -f /etc/dropbear/dropbear_dss_host_key > /dev/null 2>&1
  fi

##Compiler will insert mount commands##

  # Move existing data to new location (Compatibility fix for coming from older builds)
  if [ -e /root/xios ]; then
    echo "S10setup: Move userdata to correct location"
    rm -rf /root/.xbmc
    mv /root/xios/root/.xbmc /root/
    rm -rf /root/xios
    sync
  fi

  # Check if NetworkManager system folder exists on userdata
  if [ ! -d /root/.sysconfig/NetworkManager ] ; then
    echo -n "Creating NetworkManager .sysconfig folder... "
    mkdir -p /root/.sysconfig/NetworkManager
    cp -a /etc/NetworkManager/* /root/.sysconfig/NetworkManager/
    mount -o bind /root/.sysconfig/NetworkManager /etc/NetworkManager
  fi

  # Boot with performance, then switch to ondemand (kernel bug)
  CPU=/sys/devices/system/cpu/cpu0/cpufreq
    echo "S10setup: set cpu scaling governor"
    echo "lagfree" > $CPU/scaling_governor
    # If M1 or M3, limit to 600Mhz to keep audio hw from stalling
    echo "S10setup: set cpu scaling min/max"
    echo "600000" > $CPU/scaling_min_freq
    # M3 devices max out at 800Mhz
    echo "800000" > $CPU/scaling_max_freq

  echo "S10setup: done"
fi
