#!/bin/sh

if [ "X$1" = "Xstart" ]; then
  echo "S10setup: start"

##Compiler will insert mount commands##

  if [ ! -d /root/Data ] ; then
    echo "S10setup: Creating Data folder... "
    mkdir -pm 777 /root/Data
    sync
  fi

  # Check if NetworkManager system folder exists on userdata
  if [ ! -d /root/.sysconfig/NetworkManager ] ; then
    echo "S10setup: Creating .sysconfig folder... "
    mkdir -p /root/.sysconfig/NetworkManager
    cp -a /etc/NetworkManager/* /root/.sysconfig/NetworkManager/
    chmod 544 /root/.sysconfig/NetworkManager/dispatcher.d/*
    MAC=$(cat /sys/class/net/eth0/address)
    echo -e "[keyfile]\nunmanaged-devices=mac:$MAC" >> /root/.sysconfig/NetworkManager/NetworkManager.conf
    sync
  fi
  mount -o bind /root/.sysconfig/NetworkManager /etc/NetworkManager

  # Boot with performance, then switch to lagfree (kernel bug)
  CPU=/sys/devices/system/cpu
  for i in $CPU/cpu0/cpufreq $CPU/cpu1/cpufreq; do
    echo "S10setup: set cpu scaling governor"
    echo "lagfree" > $i/scaling_governor
    echo "S10setup: set cpu scaling min/max"
    # M6 devices min freq 200Mhz
    echo "200000" > $i/scaling_min_freq
    # M6 devices max out at 1.2-1.5Ghz depending on uboot
    echo "1320000" > $i/scaling_max_freq
  done

  echo "S10setup: done"
fi
