#!/bin/sh
#
# Start the network....
#

case "$1" in
  start)
    echo "Starting network..."

    # bump up the default udp/tcp buffersizes
    sysctl -w net.core.rmem_max=33554432
    sysctl -w net.core.netdev_max_backlog=2000
    sysctl -w net.ipv4.udp_mem='262144 327680 393216'
    sysctl -w net.ipv4.tcp_mem='262144 327680 393216'

    ifup eth0
  ;;
  stop)
    echo -n "Stopping network..."
    ifdown eth0
	;;
  restart|reload)
	"$0" stop
	"$0" start
	;;
  *)
	echo $"Usage: $0 {start|stop|restart}"
	exit 1
esac

exit $?

